import { StoreBranch, Product, StoreSettings } from "./types";

export const INITIAL_BRANCHES: StoreBranch[] = [
  {
    id: "branch-dokki",
    name: "فرع الدقي والمهندسين (الفرع الرئيسي)",
    nameEn: "Dokki & Mohandessin Main Branch",
    code: "DOKKI_MAIN",
    city: "الجيزة",
    address: "شارع مصدق تقاطع شارع السودان، الدقي",
    phone: "+201099887711",
    whatsapp: "+201099887711",
    status: "open",
    isMain: true,
    latitude: 30.0384,
    longitude: 31.2118,
    deliveryZones: ["الدقي", "المهندسين", "العجوزة", "الزمالك", "الدقي الغربي"],
    operatingHours: {
      open: "07:00",
      close: "02:00",
    },
    metrics: {
      dailyRevenue: 24850,
      dailyOrders: 68,
      activeOrders: 7,
      lowStockCount: 3,
    },
    managerName: "م. أحمد عبد الرحمن",
    managerEmail: "adminstoresupermarketinvo@gmail.com",
  },
  {
    id: "branch-nasr-city",
    name: "فرع مدينة نصر والتجمع الخامس",
    nameEn: "Nasr City & New Cairo Branch",
    code: "NASR_CITY",
    city: "القاهرة",
    address: "شارع مكرم عبيد بجوار سيتي ستارز، مدينة نصر",
    phone: "+201099887722",
    whatsapp: "+201099887722",
    status: "open",
    isMain: false,
    latitude: 30.0561,
    longitude: 31.3439,
    deliveryZones: ["مدينة نصر", "مصر الجديدة", "التجمع الأول", "التجمع الخامس", "الرحاب"],
    operatingHours: {
      open: "08:00",
      close: "01:30",
    },
    metrics: {
      dailyRevenue: 19400,
      dailyOrders: 49,
      activeOrders: 5,
      lowStockCount: 2,
    },
    managerName: "أ. محمود شاكر",
    managerEmail: "nasrcity.manager@elwadi.com",
  },
  {
    id: "branch-maadi",
    name: "فرع المعادي والمقطم",
    nameEn: "Maadi & Mokattam Branch",
    code: "MAADI",
    city: "القاهرة",
    address: "شارع النصر تقاطع اللاسلكي، دجلة المعادي",
    phone: "+201099887733",
    whatsapp: "+201099887733",
    status: "open",
    isMain: false,
    latitude: 29.9602,
    longitude: 31.2774,
    deliveryZones: ["المعادي", "دجلة", "زهراء المعادي", "المقطم", "طرة"],
    operatingHours: {
      open: "07:30",
      close: "01:00",
    },
    metrics: {
      dailyRevenue: 16200,
      dailyOrders: 38,
      activeOrders: 4,
      lowStockCount: 1,
    },
    managerName: "أ. خالد النجار",
    managerEmail: "maadi.manager@elwadi.com",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-milk-almarai-1l",
    name: "حليب المراعي كامل الدسم — 1 لتر",
    nameEn: "Almarai Full Cream Milk 1L",
    category: "الألبان والبيض",
    subCategory: "حليب طازج",
    description: "حليب المراعي الطبيعي 100%، مبستر ومعقم ومعبأ بأعلى معايير الجودة.",
    chefTips: "💡 نصيحة الشيف الذكية: استخدم الحليب دافئاً لعمل رغوة الكابتشينو الفاخرة، أو في إعداد صوص البشاميل الكريمي الناعم.",
    price: 44.0,
    originalPrice: 48.0,
    unit: "عبوة 1 لتر",
    unitStep: 1,
    barcode: "6281007010015",
    sku: "DAIRY-ALM-1L",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: false,
    discountPercentage: 8,
    rating: 4.9,
    ratingsCount: 128,
    nutritionInfo: {
      calories: 62,
      protein: "3.2g",
      fat: "3.5g",
      carbs: "4.7g",
    },
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 85, lowStockThreshold: 15, isAvailable: true, shelfLocation: "ثلاجة الألبان A1" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 62, lowStockThreshold: 15, isAvailable: true, shelfLocation: "ثلاجة الألبان B2" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 44, lowStockThreshold: 10, isAvailable: true, shelfLocation: "ثلاجة الألبان C1" },
    },
  },
  {
    id: "prod-cheese-roumi-extra",
    name: "جبن رومي مصري قديم فاخر (بطارخ)",
    nameEn: "Aged Egyptian Roumi Cheese",
    category: "الألبان والبيض",
    subCategory: "أجبان شرائح",
    description: "جبن رومي معتق أكثر من 18 شهراً يتميز بطعم قوي ومحبب ونكهة غنية أصلية.",
    chefTips: "💡 نصيحة الشيف الذكية: ابشر الجبن الرومي المعتق فوق صينية المكرونة بالبشاميل أو الحواوشي لتحصل على نكهة مصرية أصيلة مميزة.",
    price: 360.0,
    originalPrice: 390.0,
    unit: "1 كجم (يباع بالوزن)",
    unitStep: 0.25,
    barcode: "6221100234011",
    sku: "CHEESE-ROUMI-OLD",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: false,
    discountPercentage: 8,
    rating: 4.8,
    ratingsCount: 95,
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 35, lowStockThreshold: 8, isAvailable: true, shelfLocation: "قسم الجبن والأوزان" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 28, lowStockThreshold: 8, isAvailable: true, shelfLocation: "قسم الجبن والأوزان" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 20, lowStockThreshold: 5, isAvailable: true, shelfLocation: "قسم الجبن والأوزان" },
    },
  },
  {
    id: "prod-fresh-tomatoes-baladi",
    name: "طماطم بلدي طازجة مزارع الوادي",
    nameEn: "Fresh Baladi Tomatoes",
    category: "الخضروات والفواكه",
    subCategory: "خضار طازج",
    description: "طماطم طازجة يتم قطافها يومياً من مزارع الوادي الأخضر بدرجة نضج مثالية للسلطات والطبخ.",
    chefTips: "💡 نصيحة الشيف الذكية: انزع قشرة الطماطم بعد غمرها في ماء مغلي لمدة 30 ثانية لعمل صوص بيتزا إيطالي أصيل.",
    price: 18.0,
    originalPrice: 22.0,
    unit: "1 كجم",
    unitStep: 0.5,
    barcode: "6221008899001",
    sku: "VEG-TOMATO-BALADI",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: true,
    discountPercentage: 18,
    rating: 4.9,
    ratingsCount: 210,
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 150, lowStockThreshold: 30, isAvailable: true, shelfLocation: "قسم الخضار الطازج" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 120, lowStockThreshold: 25, isAvailable: true, shelfLocation: "قسم الخضار الطازج" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 95, lowStockThreshold: 20, isAvailable: true, shelfLocation: "قسم الخضار الطازج" },
    },
  },
  {
    id: "prod-olive-oil-extra-virgin",
    name: "زيت زيتون بكر ممتاز معصور على البارد — 750 مل",
    nameEn: "Extra Virgin Olive Oil 750ml",
    category: "الزيوت والمعلبات",
    subCategory: "زيوت صحية",
    description: "زيت زيتون نقي من بساتين سيناء والواحات، نسبة حموضة أقل من 0.5% غني بمضادات الأكسدة.",
    chefTips: "💡 نصيحة الشيف الذكية: أضف رشة من زيت الزيتون البكر مع الزعتر والملح الخشن على الجبنة البيضاء أو الحمص قبل التقديم مباشرة للحفاظ على كامل فوائده.",
    price: 245.0,
    originalPrice: 280.0,
    unit: "زجاجة 750 مل",
    unitStep: 1,
    barcode: "6221550998877",
    sku: "OIL-OLIVE-750ML",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: true,
    discountPercentage: 12,
    rating: 5.0,
    ratingsCount: 88,
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 40, lowStockThreshold: 10, isAvailable: true, shelfLocation: "ممر الزيوت 4" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 35, lowStockThreshold: 8, isAvailable: true, shelfLocation: "ممر الزيوت 3" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 28, lowStockThreshold: 6, isAvailable: true, shelfLocation: "ممر الزيوت 2" },
    },
  },
  {
    id: "prod-beef-minced-baladi",
    name: "لحم بقري مفروم بلدي طازج (قليل الدسم 10%)",
    nameEn: "Fresh Minced Baladi Beef",
    category: "اللحوم والدواجن",
    subCategory: "لحوم مفرومة",
    description: "لحم بقري بلدي طازج مذبوح ومجهز يومياً تحت إشراف بيطري كامل بدون أي إضافات صناعية.",
    chefTips: "💡 نصيحة الشيف الذكية: لعمل كفتة مشوية متماسكة، تبل اللحم بالبصل المصفى تماماً من الماء ورشة بهارات لحم واتركه يرتاح في الثلاجة ساعة قبل التشكيل.",
    price: 395.0,
    originalPrice: 420.0,
    unit: "1 كجم (يباع بالوزن)",
    unitStep: 0.5,
    barcode: "6221770011223",
    sku: "MEAT-BEEF-MINCED",
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: false,
    discountPercentage: 6,
    rating: 4.9,
    ratingsCount: 164,
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 30, lowStockThreshold: 10, isAvailable: true, shelfLocation: "قسم الجزارة" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 25, lowStockThreshold: 8, isAvailable: true, shelfLocation: "قسم الجزارة" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 18, lowStockThreshold: 5, isAvailable: true, shelfLocation: "قسم الجزارة" },
    },
  },
  {
    id: "prod-basmati-rice-abu-kass",
    name: "أرز بسمتي هندي طويل الحبة الشعلان — 5 كجم",
    nameEn: "Shaalan Indian Basmati Rice 5kg",
    category: "البقوليات والأرز",
    subCategory: "أرز بسمتي",
    description: "أرز بسمتي عنبر هندي نقي 100% درجة أولى، حبة طويلة لا تتكسر أثناء الطهي.",
    chefTips: "💡 نصيحة الشيف الذكية: انقع الأرز في ماء فاتر مع نصف ملعقة خل لمدة 20 دقيقة قبل الطهي لتحصل على حبات أرز طويلة ونثرية ومفلفلة كالمطاعم.",
    price: 340.0,
    originalPrice: 375.0,
    unit: "شيكارة 5 كجم",
    unitStep: 1,
    barcode: "6281001099881",
    sku: "RICE-BASMATI-5KG",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    isFeatured: true,
    isOrganic: false,
    discountPercentage: 9,
    rating: 4.9,
    ratingsCount: 142,
    branchInventory: {
      "branch-dokki": { branchId: "branch-dokki", stockQuantity: 50, lowStockThreshold: 12, isAvailable: true, shelfLocation: "ممر البقوليات والأرز" },
      "branch-nasr-city": { branchId: "branch-nasr-city", stockQuantity: 42, lowStockThreshold: 10, isAvailable: true, shelfLocation: "ممر البقوليات والأرز" },
      "branch-maadi": { branchId: "branch-maadi", stockQuantity: 30, lowStockThreshold: 8, isAvailable: true, shelfLocation: "ممر البقوليات والأرز" },
    },
  },
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  storeName: "سوبرماركت الوادي الأخضر",
  storeNameEn: "Al-Wadi Al-Akhdar Supermarket",
  chainName: "سلسلة فروع سوبرماركت الوادي الأخضر (3 فروع)",
  totalBranches: 3,
  primaryAdminEmail: "adminstoresupermarketinvo@gmail.com",
  currency: "ج.م",
  taxRate: 0.14,
  defaultDeliveryFee: 25.0,
  freeDeliveryThreshold: 450.0,
  minimumOrderAmount: 100.0,
  supportPhone: "+201099887700",
  supportWhatsApp: "+201099887700",
  loyaltyPointsRatio: 0.05,
  theme: {
    primaryColor: "#059669",
    palette: "emerald",
    fontFamily: "Tajawal, sans-serif",
  },
};
